service:
  name: secret-quotes

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-webpack
  - serverless-jest-plugin
  - serverless-offline

functions:
  login:
    handler: src/routes/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  quote:
    handler: src/routes/quotes.getQuote
    events:
      - http:
          path: quote
          method: get
          cors: true
